image: node:latest

stages:
  - backendTest
  - pages

backendTest:
    stage: backendTest
    script:
        - cd backend/
        - npm i
        - npm run test > $CI_PROJECT_DIR/backendTest_report.txt
    artifacts:
      when: always
      expire_in: 30 days
      paths:
        - backendTest_report.txt
        - backend/coverage/lcov-report/
    only:
      changes:
        - backend/*
        - .gitlab-ci.yml

pages:
  stage: pages
  script:
    - mkdir -p public
    - cp -r backend/coverage/lcov-report/* public
  artifacts:
    paths:
      - public
