image: node:latest

stages:
  - backendTest

backendTest:
    stage: backendTest
    script:
        - cd backend/
        - npm i
        - npm run test > backendTest_report.txt
    artifacts:
      when: always
      expire_in: 30 days
      paths:
        - backendTest_report.txt