image: node:latest

stages:
  - backendTest

backendTest:
    stage: backendTest
    script:
        - cd backend/
        - npm i
        - npm run test > $CI_PROJECT_DIR/backendTest_report.txt
    artifacts:
      when: always
      expire_in: 30 days
      paths:
        - backendTest_report.txt
        - coverage/*
    only:
      changes:
        - backend/*
        - .gitlab-ci.yml