const app = require('../app')
const request = require('supertest')

test('Test if user can create an acount', async () => {
  let response = await request(app)
    .post('/register')
    .send({firstName: 'Test', lastName: 'TEST', email: 'test@test.com', password: '1m02P@SsF0rt!', address: '8 rue de gaulle', birthDate: new Date('2002-09-17')})
  expect(response.statusCode).toBe(200)
})
// test('Test if user can log in and list users', async () => {
//   let response = await request(app)
//     .post('/login')
//     .send({ email: 'Sebastien.Viardot@grenoble-inp.fr', password: '123456' })
//   expect(response.statusCode).toBe(200)
//   expect(response.body).toHaveProperty('token')
//   response = await request(app)
//     .get('/api/users')
//     .set('x-access-token', response.body.token)
//   expect(response.statusCode).toBe(200)
//   expect(response.body.message).toBe('Returning users')
//   expect(response.body.data.length).toBeGreaterThan(0)
// })
